name: CI/CD FRONTEND MERN STACK CHAT APPLICATION

on:
  push:
    paths:
      - "frontend/**"
    branches: ["main","master"]
  pull_request:
    paths:
      - "frontend/**"
    branches: [main,master]

jobs:
  frontend-chat:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./frontend"
    steps:
      - name: CHECKOUT THE CODE
        uses: actions/checkout@v3
      - name: INSTALLER NODE
        uses: actions/setup-node@v3
        with:
          node-verion: '18'
      - name: INSTALLER DEPENDENCIES
        run: npm install  

      - name: RUN TEST
        run: npm test

      - name: BUILD
        run: npm run build

  test-frontend:
    runs-on: ubuntu-latest
    needs: frontend-chat
    steps:
      - uses: actions/checkout@v3
      - name: BUILD DOCKER IMAGE
        run: |
          cd frontend
          docker build -t frontend-chat .

      - name: DEPLOY
        run: echo "DEPLOY FRONTEND ..."

        
    
  