name: CI/CD CHAT APPLICATION MERN STACK
#general.yaml
on:
  push:
    paths:
      ["backend/**", "frontend/**", "services/email/**", ".github/workflows/**"]
    branches: [main, master]
  pull_request:
    paths: ["backend/**", "frontend/**", "services/email/**"]
    branches: [main, master]

jobs: # === un serveur virtuel github , chaque job tourne dans une VM differente
  test-backend:
    name: test-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # tu dit à github actions : toutes les commandes run doivent s'executer dans le dossier ./backend
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      # github telecharge ton repo dans une VM
      # ==> sans ça aucun fichier disponible
      - name: CHECKOUT THE CODE
        uses: actions/checkout@v4

      - name: INSTALLER NODE-JS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

        env:
          PORT: 5000
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
          NODE_ENV: development #if you are still development or production
          REDIS_URI: ${{ secrets.REDIS_URI }}

      - name: INSTALLER DEPENDENCIES
        run: npm install

      - name: RUN TESTS
        run: npm test

      - name: BUILD
        run: npm run build

  deploy-backend:
    name: deploy-backend
    runs-on: ubuntu-latest
    needs:
      - test-backend # deploy-backend demarre seulement si test-backend reussit

    steps:
      - uses: actions/checkout@v4
      - name: LOGIN TO DOCKER HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: BUILD IMAGE DOCKER
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-chat:latest .

      - name: PUSH DOCKER IMAGE
        run: |
          cd backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-chat:latest

      - name: DEPLOY BACKEND
        run: echo "deploy backend"

  test-frontend:
    name: test-frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: CHECKOUT THE CODE
        uses: actions/checkout@v4

      - name: INSTALLER NODE-JS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          VITE_SECRET_CRYPTAGE: ${{ secrets.VITE_SECRET_CRYPTAGE }}

      - name: INSTALLER DEPENDENCIES
        run: npm install

      - name: RUN TESTS
        run: npm test

      - name: BUILD
        run: npm run build
  deploy-frontend:
    name: deploy-frontend
    runs-on: ubuntu-latest
    needs:
      - test-frontend
    steps:
      - uses: actions/checkout@v4

      - name: LOGIN TO DOCKER HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: BUILD IMAGE DOCKER IN FRONTEND PART
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-chat:latest .
      - name: PUSH DOCKER IMAGE
        run: |
          cd frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-chat:latest

      - name: DEPLOY FRONTEND
        run: echo "deploy frontend"
  test-email-services:
    runs-on: ubuntu-latest
    name: test-email-services
    defaults:
      run:
        working-directory: ./services/test-email-services
    steps:
      - name: CHECKOUT THE CODE
        uses: actions/checkout@v4

      - name: INSTALLER NODE-JS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
        env:
          PORT_EMAIL_SERVICE: ${{ secrets.PORT_EMAIL_SERVICE }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}

      - name: INSTALLE DEPENDENCIES
        run: npm install

      - name: RUN TESTS
        run: npm  test

      - name: BUILD EMAIL SERVICE
        run: npm run build

  deploy-test-email-services:
    name: deploy email service
    runs-on: ubuntu-latest
    needs:
      - test-email-services
    steps:
      - uses: actions/checkout@v4

      - name: DOCKER LOGIN
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: BUILD DOCKER IMAGE
        run: |
          cd services/email
          docker build -t ${{ secrets.DOCKER_USERNAME }}/email_service_chat:latest .
      - name: PUSH TO DOCKER HUB
        run: |
          cd services/email
          docker push ${{ secrets.DOCKER_USERNAME }}/}/email_service_chat:latest

      - name: DEPLOY EMAIL SERVICE
        run: echo "deploy email service"
