name: CI/CD CHAT APPLICATION MERN STACK

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    name: Testing backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
  test-frontend:
    runs-on: ubuntu-latest
    name: Testing frontend
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    name: deploy all
    needs: [test-backend,test-frontend] # Attendre un job avant de demarrer
    steps:
      - uses: actions/checkout@v3
      - name: DEPLOY BACKEND AND FRONTEND
        run: |
          cd backend && docker build -t backend-chat .
          cd frontend && docker build -t frontend-chat .
          echo "All are deployed"